---
version: latest

codebattle:
  replicaCount: 1
  image:
    repository: codebattle/codebattle
    imagePullPolicy: Always

runner:
  replicaCount: 2
  image:
    repository: codebattle/runner
    imagePullPolicy: Always

nginx:
  image:
    repository: codebattle/nginx
    imagePullPolicy: Always

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
