env:
  - DOCKER_COMPOSE_VERSION=1.23.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker pull codebattle/js:10.11.0
  - docker pull codebattle/ruby:2.5.1
  - docker pull codebattle/elixir:1.7.3
  - docker pull codebattle/python:3.7.0
  - docker pull codebattle/php:7.2.0
  - docker pull codebattle/clojure:1.8.0
  - docker pull codebattle/haskell:8.4.3

jobs:
  include:
    - stage: lint and test
      script: docker-compose -f services/app/docker-compose.test.yml run sut
    - stage: build docker image with tag
      if: branch = master
      script:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
        - docker build -t codebattle/app --file services/app/Dockerfile.prod services/app/
        - docker push codebattle/app:"$TRAVICE_TAG"
