version: "3"

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: mix test
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME=postgres
      - DB_NAME=codebattle_test
    depends_on:
      - db
  db:
    image: postgres
