---
kind: Service
apiVersion: v1
metadata:
  name: "codebattle"
spec:
  selector:
    app: "codebattle"
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
