---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-frontend"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    external-dns.alpha.kubernetes.io/hostname: "codebattle.hexlet.io."
spec:
  tls:
    - hosts:
      - codebattle.hexlet.io
      secretName: certificate-frontend
  rules:
    - host: codebattle.hexlet.io
      http:
        paths:
        - backend:
            serviceName: "{{ .Release.Name }}-frontend"
            servicePort: 8080
