apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alexander.v1@hexlet.io
    privateKeySecretRef:
      name: certificate-frontend-secret
    solvers:
      - http01:
          ingress:
            class:  nginx

