apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: codebattle.hexlet.io
    http:
      paths:
      - backend:
          serviceName: "{{ .Release.Name }}-frontend"
          servicePort: 8080
