---
- hosts: all
  gather_facts: no
  tasks:
    - pip:
        name: "{{ item }}"
      with_items:
        - docker
        - docker-compose

    - template:
        src: environment.j2
        dest: '../.env'
      tags: env

    - lineinfile:
        path: /etc/hosts
        regexp: 'codebattle'
        line: '127.0.0.1 codebattle.test # codebattle'
      become: yes

